name: duacopilot
description: "DuaCopilot - AI-Powered Islamic Companion App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter

  # Core UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

  # HTTP & API Communication
  dio: ^5.4.0
  retry: ^3.1.2
  connectivity_plus: ^5.0.2
  web_socket_channel: ^2.4.0
  logger: ^2.0.2+1
  http: ^1.1.0

  # Real-Time Features & Synchronization
  socket_io_client: ^2.0.3+1
  stream_channel: ^2.1.2

  # AWS Services (replaced Firebase)
  # Authentication: AWS Cognito via custom JWT implementation
  # Storage: AWS S3 via API Gateway
  # Analytics: AWS CloudWatch via custom implementation
  # Remote Config: AWS Systems Manager Parameter Store
  # Messaging: AWS SNS/SES via API Gateway

  # State Management & Architecture
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  get_it: ^7.6.4

  # Navigation
  go_router: ^14.2.0

  # Storage & Database (Platform-Aware)
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0  # For desktop support
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # Audio & Media
  audioplayers: ^5.2.1
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  audio_service: ^0.18.12

  # Platform Integration
  url_launcher: ^6.2.2
  share_plus: ^7.2.2
  app_links: ^6.1.4
  quick_actions: ^1.0.7
  package_info_plus: ^8.3.1
  device_info_plus: ^10.1.2

  # Permissions & Speech (Mobile-Specific)
  speech_to_text: ^6.6.0
  permission_handler: ^11.0.1

  # Location & Calendar (Platform-Specific)
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  device_calendar: ^4.3.2

  # Sensors & Hardware (Mobile-Specific)
  sensors_plus: ^4.0.2
  vibration: ^1.8.4
  wakelock_plus: ^1.2.1

  # Background Tasks
  workmanager: ^0.5.2
  flutter_background_service: ^5.0.5
  flutter_background: ^1.2.0

  # Notifications
  flutter_local_notifications: ^17.2.2

  # Performance & Caching
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  image: ^4.1.7
  flutter_image_compress: ^2.1.0

  # Machine Learning & AI
  tflite_flutter: ^0.10.4
  vector_math: ^2.1.4

  # UI & Forms
  flutter_rating_bar: ^4.0.1
  form_builder_validators: ^11.0.0
  flutter_form_builder: ^9.4.1
  flutter_native_splash: ^2.3.6
  fl_chart: ^0.69.0

  # Utilities
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  dartz: ^0.10.1
  path: ^1.8.3
  timezone: ^0.9.2
  intl: ^0.19.0
  crypto: ^3.0.3
  uuid: ^4.5.1

  # Ads (Mobile Only - Handled in Code)
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Testing Framework Dependencies
  mockito: ^5.4.4
  build_runner: ^2.4.7
  flutter_driver:
    sdk: flutter
  test: ^1.24.9
  fake_async: ^1.3.1
  network_image_mock: ^2.1.1
  golden_toolkit: ^0.15.0
  
  # Performance Testing
  patrol: ^3.12.0

  # Code Generation
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  freezed: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/models/
    - assets/offline_data/
    # Local vector database assets for fast retrieval (50-200ms)
    - assets/data/quran_verses_min.json
    - assets/data/quran_embeddings_minilm.json
    # Full Quran dataset (uncomment after generation)
    - assets/data/quran_verses_full.json
    - assets/data/quran_embeddings_full.json

# Platform-aware overrides for web compatibility  
dependency_overrides:
  js: ^0.6.7
