# AWS ECS Task Definition for DuaCopilot Backend
version: "3"
services:
  duacopilot-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - AWS_REGION=us-east-1
      - DYNAMODB_TABLE_PREFIX=duacopilot-prod
    depends_on:
      - localstack
    volumes:
      - ./logs:/app/logs

  # Local DynamoDB for development
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3,sns
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./localstack-data:/tmp/localstack/data
