// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmgqH8s4N7x3YjGvZ8FQQ6C6j8m4W6tYo',
    appId: '1:123456789012:web:abcdef123456789012345678',
    messagingSenderId: '123456789012',
    projectId: 'duacopilot-dev',
    authDomain: 'duacopilot-dev.firebaseapp.com',
    storageBucket: 'duacopilot-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmgqH8s4N7x3YjGvZ8FQQ6C6j8m4W6tYo',
    appId: '1:123456789012:android:abcdef123456789012345678',
    messagingSenderId: '123456789012',
    projectId: 'duacopilot-dev',
    storageBucket: 'duacopilot-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmgqH8s4N7x3YjGvZ8FQQ6C6j8m4W6tYo',
    appId: '1:123456789012:ios:abcdef123456789012345678',
    messagingSenderId: '123456789012',
    projectId: 'duacopilot-dev',
    iosBundleId: 'com.duacopilot.dev',
    storageBucket: 'duacopilot-dev.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmgqH8s4N7x3YjGvZ8FQQ6C6j8m4W6tYo',
    appId: '1:123456789012:macos:abcdef123456789012345678',
    messagingSenderId: '123456789012',
    projectId: 'duacopilot-dev',
    iosBundleId: 'com.duacopilot.dev',
    storageBucket: 'duacopilot-dev.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmgqH8s4N7x3YjGvZ8FQQ6C6j8m4W6tYo',
    appId: '1:123456789012:windows:abcdef123456789012345678',
    messagingSenderId: '123456789012',
    projectId: 'duacopilot-dev',
    storageBucket: 'duacopilot-dev.appspot.com',
  );
}
