// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP3Eb9pvq20cgWG1RWRQViM-M52zsU-tU',
    appId: '1:387572746273:web:b776634dfccf1bffb7fb60',
    messagingSenderId: '387572746273',
    projectId: 'duacopilot',
    authDomain: 'duacopilot.firebaseapp.com',
    storageBucket: 'duacopilot.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAabJKgqwpZX3JLCx-r8-92vEwE8Zk9150',
    appId: '1:387572746273:android:ed6536fb9e94e08ab7fb60',
    messagingSenderId: '387572746273',
    projectId: 'duacopilot',
    storageBucket: 'duacopilot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDk95pODkpFZtxT-h5FaP2NrDETlV8KKM',
    appId: '1:387572746273:ios:b7088570834c4b7cb7fb60',
    messagingSenderId: '387572746273',
    projectId: 'duacopilot',
    storageBucket: 'duacopilot.firebasestorage.app',
    iosBundleId: 'com.duacopilot.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDk95pODkpFZtxT-h5FaP2NrDETlV8KKM',
    appId: '1:387572746273:ios:e8bb5f92e0444f2cb7fb60',
    messagingSenderId: '387572746273',
    projectId: 'duacopilot',
    storageBucket: 'duacopilot.firebasestorage.app',
    iosBundleId: 'com.example.duacopilot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP3Eb9pvq20cgWG1RWRQViM-M52zsU-tU',
    appId: '1:387572746273:web:dac43603ec934590b7fb60',
    messagingSenderId: '387572746273',
    projectId: 'duacopilot',
    authDomain: 'duacopilot.firebaseapp.com',
    storageBucket: 'duacopilot.firebasestorage.app',
  );

}